apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provisioner.fullname" . }}-mysql-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "provisioner.name" . }}
    chart: {{ include "provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: mysql 
data:
  mysql.cnf: |
    [mysqld]
    show_compatibility_56 = On
    query_cache_type = 1
    query_cache_size = 16M
    query_cache_limit = 1M
    general_log_file = /var/log/mysql/mysql-general.log
    general_log      = 1
    slow-query-log   = 1
    slow-query-log-file = /var/log/mysql/mysql-slow.log
