apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ include "zookeeper.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    snappyflow/plugin: zookeeper-jmx
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
  annotations:
    snappyflow/prometheus: 'true'
spec:
  ports:
  - port: {{ .Values.clientPort }}
    name: client
  - port: {{ .Values.prometheus.jmx.port }}
    name: jmxport
  selector:
    app: {{ include "zookeeper.name" . | quote }}
    release: {{ .Release.Name | quote }}
