apiVersion: v1
kind: Service
metadata:
  name: postgresql-1600344618
  labels:
    helm.sh/chart: postgresql-0.1.0
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-1600344618
    app.kubernetes.io/version: "9.6"
    app.kubernetes.io/managed-by: Helm
    snappyflow/appname: <app_name>
    snappyflow/projectname: <project_name> 
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: 9187
      name: pg-exporter

  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-1600344618

