# Default values for provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
#<SFTRACE_CONFIG> Replace <project name> and <app name> with the values configured in SnappyFlow-APM UI to which this trace is associated.
  sfappname: <app_name>
  sfprojectname: <project_name>
#<SFTRACE_CONFIG> Replace <profile_key> with actual profile key. Profile key can be got from SF-APM UI: Manage-Profiles-Copykey corresponding to your profile
  key: <profile_key> 
manager:
  nodePort: 30100
  replicaCount: 1
  image: 
    repository: snappyflowml/provisionmanager-with-sftrace
    tag: "1.0"
    pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  #annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  #name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 500m
  #   memory: 1024Mi
  # requests:
  #   cpu: 250m
  #   memory: 512Mi

autoscaling:
  enabled: false
  #minReplicas: 1
  #maxReplicas: 100
  #targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  replicaCount: 1
  strategy:
    type: Recreate
  image:
      repository: mysql
      tag: 5.7
      pullPolicy: IfNotPresent
  env: {}
  resources: 
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi

jmeter:
  enabled: true
  replicaCount: 1
  image:
      repository: justb4/jmeter
      tag: 5.1.1
      pullPolicy: IfNotPresent
  env: {}
  resources: 
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi

kafka:
  replicaCount: 1
  image:
      repository: wurstmeister/kafka
      tag: latest
      pullPolicy: IfNotPresent
  env: {}
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 1024Mi
    # requests:
    #   cpu: 250m
    #   memory: 512Mi

zookeeper:
  replicaCount: 1
  image:
      repository: mahendra0939/zookeeper-auditable
      tag: latest
      pullPolicy: IfNotPresent
  env: {}
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 1024Mi
    # requests:
    #   cpu: 250m
    #   memory: 512Mi