---
# Configure 'Deployment' of spring boot server.
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
  template:
    spec:
      initContainers:
#<SFTRACE-CONFIG>add the below init container. This copies the java agent jar to /sfagent volume mount
      - name: sftrace-java-agent
        image: busybox
        command:
        - sh
        - -c
        - -x
        - wget -O /sfagent/sftrace-agent.tar.gz https://github.com/snappyflow/apm-agent/releases/download/latest/sftrace-agent.tar.gz && cd /sfagent && tar -xvzf sftrace-agent.tar.gz && rm sftrace-agent.tar.gz
        volumeMounts:
        - mountPath: /sfagent
          name: sftrace-agent
      containers:
        - name: sample-java-app
          image: image/java-app:latest
# <SFTRACE-CONFIG>add the below "command". After java $(SFTRACE_AGENT), add application specific command to start the container. Basically, we are adding -javaagent option to the original command to start the java application
          command:
          - sh
          - -c
          - java $(SFTRACE_AGENT) <application specific commands>
#<SFTRACE-CONFIG>: example: - java $(SFTRACE_AGENT) java-app.jar 
          volumeMounts:
            - name: config-file-worker
              mountPath: /config/application.properties
              subPath: application.properties
# <SFTRACE-CONFIG>add the below volume mount. This is the location where the java agent is copied through initContainer
            - mountPath: /sfagent
              name: sftrace-agent

      ############################### environment variable ###############################
          env:
# <SFTRACE-CONFIG>add the below environment variables that will be used by the java agent
          - name: SFTRACE_PROFILE_KEY
            value: <profile_key>
          - name: SFTRACE_SERVICE_NAME
# <SFTRACE-CONFIG> replace <service_name> with appropriate service name. service_name is used to identify and filter the traces related to an application and should be named appropriately to distinctly identify it.  Service name must only contain characters from the ASCII alphabet, numbers, dashes, underscores and spaces.
            value: <service_name>
#<SFTRACE_CONFIG> Replace <project name> and <app name> with the values configured in SnappyFlow-APM UI to which this trace is associated.
          - name: SFTRACE_PROJECT_NAME
            value: <project_name>
          - name: SFTRACE_APP_NAME
            value: <app_name>
          - name: SFTRACE_AGENT
            value: -javaagent:/sfagent/sftrace/java/sftrace-java-agent.jar
# <SFTRACE-CONFIG>the below environment variables are only applicable for springmvc and optional. More information available in the documentation. Refere to HTTPCOnfiguration Options
          - name: ELASTIC_APM_DISABLE_INSTRUMENTATIONS
            value: spring-mvc
          - name: ELASTIC_APM_USE_PATH_AS_TRANSACTION_NAME
            value: "true"
#Replace <normalized urls> with appropriate urls. Transactions can be filtered by normalized url in SnappyFlow-APM UI
          - name: ELASTIC_APM_URL_GROUPS
            value: <normalized_urls>


      #####################################################################################
      volumes:
 # <SFTRACE-CONFIG> add the below volume
        - name: sftrace-agent
          emptyDir: {}