{{- if .Values.prometheus.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kafka.fullname" . }}-exporter
  labels:
    app: {{ template "kafka.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    role: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "kafka.name" . }}-exporter
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
{{- if and .Values.prometheus.kafka.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.prometheus.kafka.port | quote }}
{{- end }}
      labels:
        app: {{ template "kafka.name" . }}-exporter
        release: {{ .Release.Name }}
        role: exporter
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    spec:
      containers:
      - image: "{{ .Values.prometheus.kafka.image }}:{{ .Values.prometheus.kafka.imageTag }}"
        name: kafka-exporter
        args:
          - --kafka.server={{ template "kafka.fullname" . }}:9092
          - --web.listen-address=:{{ .Values.prometheus.kafka.port }}
        ports:
          - containerPort: {{ .Values.prometheus.kafka.port }}
        resources:
{{ toYaml .Values.prometheus.kafka.resources | indent 10 }}
{{- end }}
