{{- if .Values.jmeter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "provisioner.fullname" . }}-jmeter
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "provisioner.name" . }}
    chart: {{ include "provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: jmeter
spec:
  replicas: {{ .Values.jmeter.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "provisioner.name" . }}
      release: {{ .Release.Name }}
      {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
      {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
      snappyflow/component: jmeter
  template:
    metadata:
      labels:
        app: {{ include "provisioner.name" . }}
        release: {{ .Release.Name }}
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
        snappyflow/component: jmeter
      annotations:
        {{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
      initContainers:
        - name: get-jar-files
          image: alpine
          command:
            - sh
            - -c
            - -x
            - apk add --no-cache curl && curl ${JOLOKIA_JAR_URL} -o /data/jolokia.jar && curl ${MYSQL_CONNECTOR} -o /data/mysql-connector.tar.gz && tar -zxvf /data/mysql-connector.tar.gz mysql-connector-java-8.0.18/mysql-connector-java-8.0.18.jar -C /data
          env:
            - name: JOLOKIA_JAR_URL
              value: https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar
            - name: MYSQL_CONNECTOR
              value: https://cdn.mysql.com/archives/mysql-connector-java-8.0/mysql-connector-java-8.0.18.tar.gz
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: {{ .Chart.Name }}-jmeter
          image: "{{ .Values.jmeter.image.repository }}:{{ .Values.jmeter.image.tag }}"
          imagePullPolicy: {{ .Values.jmeter.image.pullPolicy }}
          command:
            - sh 
            - -c 
            - -x 
            - cp /data/mysql-connector-java-8.0.18/mysql-connector-java-8.0.18.jar /opt/apache-jmeter-5.1.1/lib/.; cp /data/jolokia.jar /opt/apache-jmeter-5.1.1/lib/. && touch /var/log/test_plan.jtl; cd $JMETER_HOME/bin && /usr/bin/java -server $JAVA_ARGS $JVM_ARGS $JAVA_AGENT -jar $JMETER_HOME/bin/ApacheJMeter.jar -n -t /scripts/test_plan.jmx -l /var/log/test_plan.jtl -LINFO -j /var/log/jmeter.log -Jserver=${PROVISIONER_HOST};
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PROVISIONER_HOST
              value: {{ include "provisioner.fullname" . }}-manager-service
            - name: PROVISIONER_PORT
              value: "8080"
            - name: JMETER_HOME
              value: "/opt/apache-jmeter-5.1.1"
            - name: JVM_ARGS
              value: "-Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=5555 -Dcom.sun.management.jmxremote.rmi.port=5555 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
            - name: JAVA_ARGS
              value: "-XX:+HeapDumpOnOutOfMemoryError -Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:G1ReservePercent=20 -Djava.security.egd=file:/dev/urandom -Duser.language=en -Duser.region=EN"
            # - name: JAVA_AGENT
            #   value: "-javaagent:/opt/apache-jmeter-5.1.1/lib/jolokia.jar=port=8778,host=0.0.0.0"
            {{- range $key, $value := .Values.jmeter.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: scripts
              mountPath: /scripts
            - name: jmeterlog
              mountPath: /var/log
          resources:
{{ toYaml .Values.jmeter.resources | indent 12 }}
      volumes:
        - name: data
          emptyDir: {}
        - name: scripts
          configMap:
            name: {{ include "provisioner.fullname" . }}-scripts
        - name: jmeterlog
          emptyDir: {}
{{- end }}