# {{- if .Values.jmeter.enabled }}
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ template "provisioner.fullname" . }}-jmeter
#   namespace: {{ .Release.Namespace | quote }}
#   labels:
#     app: {{ template "provisioner.name" . }}
#     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#     release: "{{ .Release.Name }}"
#     heritage: "{{ .Release.Service }}"
#     {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
#     {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
#     snappyflow/component: jmeter
# spec:
#   type: ClusterIP
#   selector:
#     app: {{ template "provisioner.name" . }}
#     release: {{ .Release.Name | quote }}
#     snappyflow/component: jmeter
# {{- end }}
