---
# Define a 'Service' to expose manager to other services.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "provisioner.fullname" . }}-manager-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "provisioner.name" . }}
    chart: {{ include "provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: manager
spec:
  # type: NodePort
  ports:
    # - nodePort: {{ .Values.manager.nodePort }}
    - name: manager-port
      port: 8080
      targetPort: {{ .Values.manager.targetPort }}
  {{- if .Values.manager.jmx_exporter.enabled }}
    - name: jmx-exporter
      port: {{ .Values.manager.jmx_exporter.port }}
      targetPort: jmx-exporter
  {{- end }}
  selector:
    app: {{ include "provisioner.name" . }}
    chart: {{ include "provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: manager
  type: ClusterIP
