apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "provisioner.name" . }}
    chart: {{ include "provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: mysql
    tier: database
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/mnt/data"