---
# Define a 'Persistent Volume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim                        # name of PVC essential for identifying the storage data
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "provisioner.name" . }}
    chart: {{ include "provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce                           # this specifies the mode of the claim that we are trying to create
  resources:
    requests:
      storage: 500Mi                          # this will tell kubernetes about the amount of space we are trying to claim
  storageClassName: "manual"                 