---
# Configure 'Deployment' of spring boot server.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "provisioner.fullname" . }}-worker
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "provisioner.name" . }}
    chart: {{ include "provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    snappyflow/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "provisioner.name" . }}
      chart: {{ include "provisioner.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
      {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
      snappyflow/component: worker
  template:
    metadata:
      labels:
        app: {{ include "provisioner.name" . }}
        chart: {{ include "provisioner.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
        snappyflow/component: worker
    spec:
      initContainers:
        - name: sftrace-java-agent
          image: busybox
          command:
          - sh
          - -c
          - -x
          - wget -O /sfagent/sftrace-agent.tar.gz https://github.com/snappyflow/apm-agent/releases/download/latest/sftrace-agent.tar.gz && cd /sfagent && tar -xvzf sftrace-agent.tar.gz && rm sftrace-agent.tar.gz
          volumeMounts:
          - mountPath: /sfagent
            name: sftrace-agent
      containers:
        - name: {{ .Chart.Name }}-worker
          image: {{ .Values.worker.image.repository }}:{{.Values.worker.image.tag}}              # spring boot application image
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command:
            - sh
            - -c
            - java $(SFTRACE_AGENT) ${JMX_OPTS} -jar worker.jar     
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: sftrace-agent
              mountPath: /sfagent
            - name: config-file-worker
              mountPath: /config/application.properties
              subPath: application.properties
      ############################### environment variable ###############################
          env:
            - name: SFTRACE_PROFILE_KEY
              value: {{ .Values.global.key }}
            - name: SFTRACE_SERVICE_NAME
              value: "provision-worker"
            - name: SFTRACE_PROJECT_NAME
              value: {{ .Values.global.sfprojectname }}
            - name: SFTRACE_APP_NAME
              value: {{ .Values.global.sfappname }}
            - name: SFTRACE_AGENT
              value: -javaagent:/sfagent/sftrace/java/sftrace-java-agent.jar
            - name: ELASTIC_APM_DISABLE_INSTRUMENTATIONS
              value: spring-mvc
            - name: ELASTIC_APM_USE_PATH_AS_TRANSACTION_NAME
              value: "true"
  #Replace <normalized urls> with appropriate urls. Transactions can be filtered by normalized url in SnappyFlow-APM UI
            - name: ELASTIC_APM_URL_GROUPS
              value: /api/provision/delete-all,/api/provision/*,/api/worker/get-counter/*,/api/worker/reset-counter/*,/reset-counter/*
            - name: JMX_PORT
              value: "5555"
            - name: JMX_OPTS
              value: "-Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.local.only=false	-Dcom.sun.management.jmxremote.port=5555 -Dcom.sun.management.jmxremote.rmi.port=5555 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
      #####################################################################################
{{- if .Values.worker.jmx_exporter.enabled }}
        - name: jmx-exporter
          image: "{{ .Values.worker.jmx_exporter.image.repository }}:{{ .Values.worker.jmx_exporter.image.tag }}"
          imagePullPolicy: {{ .Values.worker.jmx_exporter.image.pullPolicy | quote }}
          command:
            - sh
            - -c
            - -x
            - java -jar /opt/bitnami/jmx-exporter/jmx_prometheus_httpserver.jar {{ .Values.worker.jmx_exporter.port }} /config/jmx-config.yml
          ports:
          - name: jmx-exporter
            containerPort: {{ .Values.worker.jmx_exporter.port }}
          volumeMounts:
            - name: jmx-exporter
              mountPath: /config/jmx-config.yml
              subPath: jmx-config.yml
          livenessProbe:
            httpGet:
              path: /metric
              port: jmx-exporter
            initialDelaySeconds: 90
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /metric
              port: jmx-exporter
            initialDelaySeconds: 60
            timeoutSeconds: 20
{{- end }}
      volumes:
        - name: config-file-worker
          configMap:
            name: worker-application-properties
        - name: sftrace-agent
          emptyDir: {}
{{- if .Values.worker.jmx_exporter.enabled }}
        - name: jmx-exporter
          configMap:
            name: {{ include "provisioner.fullname" . }}-jmx-exporter
{{- end }}
